# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

"""Generate top-level documentation pages from per-plugin documentation."""

from __future__ import annotations

import argparse
import json
import re
import shutil
import sys
import tempfile
from dataclasses import dataclass
from html import escape
from pathlib import Path

from ddp._repo import find_repo_root, load_toml

GENERATED_NOTICE = "<!-- Auto-generated by `uv run ddp plugin-docs`. Do not edit directly. -->"
NAV_START_TOKEN = "# BEGIN GENERATED PLUGIN DOCS NAV"
NAV_END_TOKEN = "# END GENERATED PLUGIN DOCS NAV"


@dataclass(frozen=True)
class PluginDocs:
    """Metadata needed to publish one plugin's documentation.

    Args:
        package_name: Python distribution name from the plugin pyproject.
        docs_slug: URL-safe directory name used under ``docs/plugins``.
        version: Package version from plugin metadata.
        description: Package description from plugin metadata.
        column_types: Data Designer entry point keys exposed by the plugin.
        plugin_dir: Source plugin package directory.
        source_docs_dir: Optional source documentation directory.
    """

    package_name: str
    docs_slug: str
    version: str
    description: str
    column_types: tuple[str, ...]
    plugin_dir: Path
    source_docs_dir: Path | None


@dataclass(frozen=True)
class NavPage:
    """One generated Zensical navigation page entry.

    Args:
        title: Navigation title.
        path: Markdown path relative to the top-level docs directory.
    """

    title: str
    path: str


def normalize_docs_slug(package_name: str) -> str:
    """Normalize a package name into a stable docs URL path segment.

    Args:
        package_name: Python package distribution name.

    Returns:
        URL-safe slug suitable for ``docs/plugins/<slug>``.
    """
    slug = re.sub(r"[^A-Za-z0-9_.-]+", "-", package_name.lower()).strip("-")
    return slug or "plugin"


def discover_plugin_docs(repo_root: Path) -> list[PluginDocs]:
    """Discover plugin metadata and optional documentation source directories.

    Args:
        repo_root: Repository root containing ``plugins/``.

    Returns:
        Sorted plugin documentation metadata.
    """
    plugins_dir = repo_root / "plugins"
    plugins: list[PluginDocs] = []
    seen_slugs: set[str] = set()

    for toml_path in sorted(plugins_dir.glob("*/pyproject.toml")):
        data = load_toml(toml_path)
        project = data.get("project", {})
        package_name = str(project.get("name", toml_path.parent.name))
        docs_slug = normalize_docs_slug(package_name)
        if docs_slug in seen_slugs:
            raise ValueError(f"Duplicate generated plugin docs slug: {docs_slug}")
        seen_slugs.add(docs_slug)

        entry_points = project.get("entry-points", {}).get("data_designer.plugins", {})
        source_docs_dir = toml_path.parent / "docs"
        plugins.append(
            PluginDocs(
                package_name=package_name,
                docs_slug=docs_slug,
                version=str(project.get("version", "unknown")),
                description=str(project.get("description", "")),
                column_types=tuple(sorted(str(key) for key in entry_points)),
                plugin_dir=toml_path.parent,
                source_docs_dir=source_docs_dir if source_docs_dir.is_dir() else None,
            )
        )

    return sorted(plugins, key=lambda plugin: plugin.package_name)


def format_markdown_code_list(values: tuple[str, ...]) -> str:
    """Format values as a comma-separated Markdown code list.

    Args:
        values: Values to format.

    Returns:
        Markdown inline code list, or a fallback sentence when empty.
    """
    if not values:
        return "None declared"
    return ", ".join(f"`{value}`" for value in values)


def format_html_code_list(values: tuple[str, ...]) -> str:
    """Format values as a comma-separated HTML code list.

    Args:
        values: Values to format.

    Returns:
        HTML inline code list, or a fallback sentence when empty.
    """
    if not values:
        return "No entry points"
    return ", ".join(f"<code>{escape(value)}</code>" for value in values)


def format_html_chips(values: tuple[str, ...]) -> str:
    """Format values as card badge chips.

    Args:
        values: Values to format.

    Returns:
        HTML span chips, or a fallback chip when empty.
    """
    if not values:
        return '<span class="plugin-doc-chip plugin-doc-chip--muted">No entry points</span>'
    return "".join(f'<span class="plugin-doc-chip">{escape(value)}</span>' for value in values)


def render_plugins_index(plugins: list[PluginDocs], repo_root: Path) -> str:
    """Render the generated plugin documentation landing page.

    Args:
        plugins: Discovered plugin documentation metadata.
        repo_root: Repository root used to format source paths.

    Returns:
        Markdown page content.
    """
    lines = [
        GENERATED_NOTICE,
        "",
        "# Plugins",
        "",
        "Browse available Data Designer plugins by what they add to your data generation workflow.",
        "",
    ]

    if not plugins:
        lines.append("No plugins were discovered under `plugins/`.")
        return "\n".join(lines) + "\n"

    lines.append('<div class="plugin-doc-grid">')
    for plugin in plugins:
        lines.extend(
            [
                f'  <a class="plugin-doc-card" href="{escape(plugin.docs_slug)}/" '
                f'aria-label="Open {escape(plugin.package_name)} documentation">',
                '    <span class="plugin-doc-card__header">',
                f'      <span class="plugin-doc-card__title">{escape(plugin.package_name)}</span>',
                f'      <span class="plugin-doc-card__version">v{escape(plugin.version)}</span>',
                "    </span>",
                f'    <span class="plugin-doc-card__description">{escape(plugin.description)}</span>',
                '    <span class="plugin-doc-card__section">',
                '      <span class="plugin-doc-card__label">Column types</span>',
                f'      <span class="plugin-doc-card__chips">{format_html_chips(plugin.column_types)}</span>',
                "    </span>",
                '    <span class="plugin-doc-card__cta">Open plugin docs</span>',
                "  </a>",
            ]
        )
    lines.append("</div>")
    return "\n".join(lines) + "\n"


def render_fallback_plugin_page(plugin: PluginDocs, repo_root: Path) -> str:
    """Render a metadata fallback page for a plugin without docs content.

    Args:
        plugin: Plugin metadata.
        repo_root: Repository root.

    Returns:
        Markdown page content.
    """
    source_path = plugin.plugin_dir.relative_to(repo_root).as_posix()
    lines = [
        GENERATED_NOTICE,
        "",
        f"# {plugin.package_name}",
        "",
    ]
    if plugin.description:
        lines.extend([plugin.description, ""])

    lines.extend(
        [
            "This page is generated from package metadata because the plugin has not added",
            f"custom documentation under `{source_path}/docs/` yet.",
            "",
            "## Metadata",
            "",
            f"- Version: `{plugin.version}`",
            f"- Column types: {format_markdown_code_list(plugin.column_types)}",
            "",
            "## Installation",
            "",
            "```bash",
            f"pip install {plugin.package_name}",
            "```",
            "",
        ]
    )
    return "\n".join(lines)


def should_copy_doc_file(path: Path) -> bool:
    """Return whether a plugin documentation file should be copied.

    Args:
        path: Source file path.

    Returns:
        True when the file should be included in generated docs.
    """
    ignored_parts = {"__pycache__", ".pytest_cache"}
    return not any(part in ignored_parts or part.startswith(".") for part in path.parts)


def destination_doc_relative_path(source_path: Path, source_root: Path, has_index: bool) -> Path:
    """Map a plugin docs source file to its generated relative path.

    Args:
        source_path: Source documentation file.
        source_root: Root plugin documentation directory.
        has_index: Whether the plugin source already contains ``index.md``.

    Returns:
        Relative path under ``docs/plugins/<plugin>``.
    """
    relative_path = source_path.relative_to(source_root)
    if relative_path == Path("README.md") and not has_index:
        return Path("index.md")
    return relative_path


def copy_plugin_docs(plugin: PluginDocs, destination_dir: Path) -> None:
    """Copy a plugin's authored documentation into the generated docs tree.

    Args:
        plugin: Plugin metadata and source docs location.
        destination_dir: Generated docs directory for this plugin.
    """
    if plugin.source_docs_dir is None:
        return

    has_index = (plugin.source_docs_dir / "index.md").is_file()
    for source_path in sorted(plugin.source_docs_dir.rglob("*")):
        if not source_path.is_file() or not should_copy_doc_file(source_path.relative_to(plugin.source_docs_dir)):
            continue
        relative_path = destination_doc_relative_path(source_path, plugin.source_docs_dir, has_index)
        target_path = destination_dir / relative_path
        target_path.parent.mkdir(parents=True, exist_ok=True)
        shutil.copy2(source_path, target_path)


def write_text(path: Path, content: str) -> None:
    """Write UTF-8 text after ensuring the parent directory exists.

    Args:
        path: Destination file path.
        content: File content.
    """
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")


def build_plugin_docs_tree(repo_root: Path, plugins: list[PluginDocs], destination_dir: Path) -> None:
    """Build the generated ``docs/plugins`` tree.

    Args:
        repo_root: Repository root.
        plugins: Discovered plugin documentation metadata.
        destination_dir: Generated plugin docs output directory.
    """
    destination_dir.mkdir(parents=True, exist_ok=True)
    write_text(destination_dir / "index.md", render_plugins_index(plugins, repo_root))

    for plugin in plugins:
        plugin_destination = destination_dir / plugin.docs_slug
        plugin_destination.mkdir(parents=True, exist_ok=True)
        copy_plugin_docs(plugin, plugin_destination)
        if not (plugin_destination / "index.md").is_file():
            write_text(plugin_destination / "index.md", render_fallback_plugin_page(plugin, repo_root))


def markdown_title_fallback(relative_path: Path) -> str:
    """Create a readable title from a Markdown relative path.

    Args:
        relative_path: Markdown path relative to a plugin docs root.

    Returns:
        Human-readable fallback title.
    """
    if relative_path.name in {"index.md", "README.md"}:
        return "Overview"
    name = relative_path.with_suffix("").as_posix().replace("/", " / ")
    words = re.split(r"[-_ ]+", name)
    return " ".join(word.capitalize() for word in words if word)


def extract_markdown_title(path: Path, fallback: str) -> str:
    """Extract the first H1 title from a Markdown file.

    Args:
        path: Markdown source path.
        fallback: Title to use when no H1 is present.

    Returns:
        Extracted or fallback title.
    """
    if path.name in {"index.md", "README.md"}:
        return "Overview"

    try:
        lines = path.read_text(encoding="utf-8").splitlines()
    except UnicodeDecodeError:
        return fallback

    for line in lines:
        stripped = line.strip()
        if stripped.startswith("# "):
            title = stripped[2:].strip().strip("#").strip()
            if title:
                return title
    return fallback


def collect_plugin_nav_pages(plugin_docs_dir: Path, docs_root: Path) -> list[NavPage]:
    """Collect generated Markdown pages for one plugin's nav section.

    Args:
        plugin_docs_dir: Generated docs directory for a plugin.
        docs_root: Top-level docs directory.

    Returns:
        Zensical navigation pages sorted with index pages first.
    """
    pages: list[tuple[tuple[int, str], NavPage]] = []
    for page_path in sorted(plugin_docs_dir.rglob("*.md")):
        relative_path = page_path.relative_to(plugin_docs_dir)
        fallback = markdown_title_fallback(relative_path)
        title = extract_markdown_title(page_path, fallback)
        docs_path = page_path.relative_to(docs_root).as_posix()
        sort_key = (0 if relative_path.name in {"index.md", "README.md"} else 1, relative_path.as_posix())
        pages.append((sort_key, NavPage(title=title, path=docs_path)))
    return [page for _, page in sorted(pages, key=lambda item: item[0])]


def toml_string(value: str) -> str:
    """Format a string for use in generated TOML.

    Args:
        value: String value.

    Returns:
        Double-quoted TOML-compatible string.
    """
    return json.dumps(value)


def render_plugin_nav_entries(plugin_docs_root: Path, docs_root: Path, plugins: list[PluginDocs]) -> list[str]:
    """Render plugin entries inside the generated Zensical nav block.

    Args:
        plugin_docs_root: Generated ``docs/plugins`` root.
        docs_root: Top-level docs directory.
        plugins: Discovered plugin documentation metadata.

    Returns:
        Lines to insert between nav block markers.
    """
    lines: list[str] = []
    for plugin in plugins:
        pages = collect_plugin_nav_pages(plugin_docs_root / plugin.docs_slug, docs_root)
        lines.append(f"    {{{toml_string(plugin.package_name)} = [")
        for page in pages:
            lines.append(f"      {{{toml_string(page.title)} = {toml_string(page.path)}}},")
        lines.append("    ]},")
    return lines


def replace_generated_nav_block(config_text: str, generated_lines: list[str]) -> str:
    """Replace the generated plugin docs nav block in ``zensical.toml``.

    Args:
        config_text: Current configuration file content.
        generated_lines: Replacement lines for the generated block.

    Returns:
        Updated configuration text.
    """
    lines = config_text.splitlines()
    start_indexes = [index for index, line in enumerate(lines) if NAV_START_TOKEN in line]
    end_indexes = [index for index, line in enumerate(lines) if NAV_END_TOKEN in line]

    if len(start_indexes) != 1 or len(end_indexes) != 1:
        raise ValueError(
            f"zensical.toml must contain exactly one {NAV_START_TOKEN!r} and one {NAV_END_TOKEN!r} marker."
        )

    start = start_indexes[0]
    end = end_indexes[0]
    if end <= start:
        raise ValueError(f"{NAV_END_TOKEN!r} must appear after {NAV_START_TOKEN!r}.")

    updated_lines = lines[: start + 1] + generated_lines + lines[end:]
    return "\n".join(updated_lines) + "\n"


def render_zensical_config(
    config_path: Path,
    plugin_docs_root: Path,
    plugins: list[PluginDocs],
    docs_root: Path | None = None,
) -> str:
    """Render ``zensical.toml`` with current generated plugin navigation.

    Args:
        config_path: Path to ``zensical.toml``.
        plugin_docs_root: Generated ``docs/plugins`` root.
        plugins: Discovered plugin documentation metadata.
        docs_root: Optional top-level docs directory for computing nav paths.

    Returns:
        Updated Zensical configuration content.
    """
    nav_docs_root = docs_root or config_path.parent / "docs"
    generated_lines = render_plugin_nav_entries(plugin_docs_root, nav_docs_root, plugins)
    return replace_generated_nav_block(config_path.read_text(encoding="utf-8"), generated_lines)


def list_relative_files(root: Path) -> set[Path]:
    """List files under a root as relative paths.

    Args:
        root: Directory to inspect.

    Returns:
        Set of relative file paths.
    """
    if not root.exists():
        return set()
    return {path.relative_to(root) for path in root.rglob("*") if path.is_file()}


def compare_generated_tree(expected_dir: Path, actual_dir: Path) -> list[str]:
    """Compare the generated docs tree with the checked-in docs tree.

    Args:
        expected_dir: Temporary expected generated tree.
        actual_dir: Actual generated tree under the repo docs directory.

    Returns:
        Human-readable drift messages.
    """
    drift: list[str] = []
    expected_files = list_relative_files(expected_dir)
    actual_files = list_relative_files(actual_dir)

    for relative_path in sorted(expected_files - actual_files):
        drift.append(f"missing generated docs file: {actual_dir / relative_path}")
    for relative_path in sorted(actual_files - expected_files):
        drift.append(f"stale generated docs file: {actual_dir / relative_path}")
    for relative_path in sorted(expected_files & actual_files):
        if (expected_dir / relative_path).read_bytes() != (actual_dir / relative_path).read_bytes():
            drift.append(f"outdated generated docs file: {actual_dir / relative_path}")

    return drift


def check_plugin_docs(repo_root: Path) -> list[str]:
    """Check whether generated plugin documentation files are current.

    Args:
        repo_root: Repository root.

    Returns:
        Human-readable drift messages.
    """
    plugins = discover_plugin_docs(repo_root)
    actual_plugin_docs_root = repo_root / "docs" / "plugins"

    with tempfile.TemporaryDirectory() as tmp_dir:
        expected_plugin_docs_root = Path(tmp_dir) / "plugins"
        build_plugin_docs_tree(repo_root, plugins, expected_plugin_docs_root)
        drift = compare_generated_tree(expected_plugin_docs_root, actual_plugin_docs_root)
        expected_config = render_zensical_config(
            repo_root / "zensical.toml",
            expected_plugin_docs_root,
            plugins,
            docs_root=expected_plugin_docs_root.parent,
        )

    if (repo_root / "zensical.toml").read_text(encoding="utf-8") != expected_config:
        drift.append("outdated generated plugin docs navigation in zensical.toml")

    return drift


def sync_plugin_docs(repo_root: Path) -> list[PluginDocs]:
    """Regenerate plugin documentation pages and Zensical navigation.

    Args:
        repo_root: Repository root.

    Returns:
        Discovered plugins included in the generated docs.
    """
    plugins = discover_plugin_docs(repo_root)
    plugin_docs_root = repo_root / "docs" / "plugins"

    if plugin_docs_root.exists():
        shutil.rmtree(plugin_docs_root)

    build_plugin_docs_tree(repo_root, plugins, plugin_docs_root)
    config_path = repo_root / "zensical.toml"
    config_path.write_text(render_zensical_config(config_path, plugin_docs_root, plugins), encoding="utf-8")
    return plugins


def main(args: list[str] | None = None) -> int:
    """Run the plugin documentation generator CLI.

    Args:
        args: Optional command line arguments.

    Returns:
        Process exit code.
    """
    parser = argparse.ArgumentParser(description="Generate plugin documentation pages for Zensical")
    parser.add_argument(
        "--check",
        action="store_true",
        help="Check generated plugin docs without modifying files",
    )
    parsed_args = parser.parse_args(args)
    repo_root = find_repo_root()

    if parsed_args.check:
        drift = check_plugin_docs(repo_root)
        if drift:
            print("Generated plugin documentation is out of date. Run `make plugin-docs`.", file=sys.stderr)
            for message in drift:
                print(f"  - {message}", file=sys.stderr)
            return 1
        print("Generated plugin documentation is current.")
        return 0

    plugins = sync_plugin_docs(repo_root)
    print(f"Generated plugin documentation for {len(plugins)} plugin(s).")
    return 0


if __name__ == "__main__":
    sys.exit(main())
