# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

ARG PISTON_IMAGE=ghcr.io/engineer-man/piston:latest
FROM ${PISTON_IMAGE}

EXPOSE 2000
